Add Mermaid Flowchart serializer
bitwalker/libgraph pull request #66
Opened 2023-02-04 19:29 UTC by andersonmcook

Adds a serializer for [Mermaid](https://mermaid.js.org/) [Flowcharts](https://mermaid.js.org/syntax/flowchart.html)

```mermaid
flowchart
    97["start"]
    98["{:complex, :label}"]
    99["c"]
    100["finish"]
    97 ----> 98
    98 --> |5| 99
    98 ----> |1.0| 100
    99 --> 100
```

2023-03-03 23:01 UTC, hauleth requested changes

2023-03-03 23:01 UTC, hauleth commented on lib/graph/serializers/flowchart.ex
> +    """
I think that this serialiser should not assume that it will produce Markdown and instead it should produce raw Mermaid output and leave formatting for output document to the user.

2023-03-03 23:12 UTC, andersonmcook commented on lib/graph/serializers/flowchart.ex
> +    """
I think that's a completely fair ask. My assumption was it would require the user to type out the codeblock more often than not.

2023-07-04 14:54 UTC, lorenzosinisi commented
Is this ready to be merged? Would love to have this upstream ❤️

2023-07-04 14:56 UTC, hauleth commented on lib/graph/serializers/flowchart.ex
> +    """
@andersonmcook yeah, but that make it pain if it is used in any other environment that is not Markdown. Additionally it assumes that the Markdown processor will use exactly the same syntax as the GitHub is using for their Mermaid diagrams. That is quite a lot of assumptions there.

2023-07-04 15:02 UTC, lorenzosinisi commented on lib/graph/serializers/flowchart.ex
> +    """
Renaming this module `MermaidFlowchart` would also help clarify what is the output of this module. What do you think?

2023-07-04 16:01 UTC, bitwalker approved these changes
Thanks!

2023-07-04 16:01 UTC, merged