add leaf_vertices function
bitwalker/libgraph pull request #69
Opened 2023-06-26 08:11 UTC by mmmries

This is a rough draft to address https://github.com/bitwalker/libgraph/issues/68

I don't have a lot of experience with graph theory, so I wasn't sure if the idea of `leaf_vertices` usually includes root nodes? This current implementation only includes vertices that have an edge pointing to them, and no outgoing edges. In my application code I have a recursive process that scans for leaf vertices that need to be resolved and when there are no leaf vertices left it just grabs all remaining vertices to finish it's work.

2023-07-04 16:19 UTC, bitwalker requested changes
Looks good, just a small change and I'll get this merged!

2023-07-04 16:19 UTC, bitwalker commented on lib/graph/directed.ex
> +  def leaf_vertices(%Graph{in_edges: ie, out_edges: oe} = g) do
I'd like to have a doc comment explaining the purpose/example use case for this function to help users understand what it might be useful for. I think we should probably also dispatch on whether the graph is directed or not, and if undirected, raise an error, as this function is non-sensical for undirected graphs. We need to do a bit of an overhaul for undirected graphs in general, so it might actually be better to not define a delegate in the `Graph` module for now, as that is likely to be the way we handle functions which have a specific directionality.

2023-07-05 08:10 UTC, mmmries commented on lib/graph/directed.ex
> +  def leaf_vertices(%Graph{in_edges: ie, out_edges: oe} = g) do
👍 that makes sense. I wondered about whether it should live at the `Graph` level anyway, but saw a handful of other functions that seemed to exist in both. I agree with the direction and I'll adjust so this is only applicable to `Graph.Directed`

Should I go ahead and remove the `@moduledoc false` from that graph? I could writeup a simple moduledoc for that or I can just leave this new function undocumented until you get a chance to write something that captures your intent for the module more long-term?

2023-07-05 19:14 UTC, bitwalker commented on lib/graph/directed.ex
> +  def leaf_vertices(%Graph{in_edges: ie, out_edges: oe} = g) do
I'm working on refactoring things to make better use of the separate graph modules, so don't worry about making any changes at that level, I'll take care of that when I'm done with those other changes.

2023-07-06 11:42 UTC, mmmries commented on lib/graph/directed.ex
> +  def leaf_vertices(%Graph{in_edges: ie, out_edges: oe} = g) do
👍 I pushed up a commit that ads a docstring with example doctest, raises an `ArgumentError` for undirected graphs and also simplifies the implementation a bit by defining `leaf_vertices` as all vertices with no outgoing edges. I think this is a more useful definition when considering cases like:

```elixir
[:a] = Graph.new() |> Graph.add_vertex(:a) |> Graph.leaf_vertices()
```

2023-07-17 14:22 UTC, mmmries commented
Let's hold of on this change. I was doing some testing and I found that in some cases the edge indices contain a key, but with an empty `MapSet`. This seems to happen when we add and then later remove vertices.

2023-08-02 09:37 UTC, mmmries commented
it looks like my project is going to take another direction for managing a set of dependencies, so I'll close this PR.

One thing I thought I would mention is that in ran into the fact that `delete_vertex` has a cost proportional to the size of the overall graph because the code enumerates through the entire `in_edges` and `out_edges` map for each vertex delete. I think this could be improved by only checking the edges that are incoming to or outgoing from the vertex being deleted.

This performance may not matter for many or most use-cases of a graph, but in my use case where I'm iteratively discovering and pruning the leaf vertices, it was a performance bottleneck.

Thanks again for the awesome library among all your other community contributions @bitwalker ❤️ 💛 💙 💚 💜

2023-08-02 09:37 UTC, closed without merging